### ISSUE TITLE
内容缺失

### ISSUE THREAD

**Issue by heistings** [linsyorozuya/avfoundation-programming-guide#2]
原文：

To set capture properties on a device, you must first acquire a lock on the device using lockForConfiguration:. This avoids making changes that may be incompatible with settings in other applications. The following code fragment illustrates how to approach changing the focus mode on a device by first determining whether the mode is supported, then attempting to lock the device for reconfiguration. The focus mode is changed only if the lock is obtained, and the lock is released immediately afterward.

译文：

要修改设备的捕捉属性, 首先需要使用方法 [lockForConfiguration:](https://developer.apple.com/reference/avfoundation/avcapturedevice/1387810-lockforconfiguration) 锁定设备, 这样可以避免与其他应用的设置产生冲突.

**Comment by Ohuisang** [comment]
谢谢，补了下。
